platform: x64

environment:
  ANACONDA_TOKEN:
    secure: mr-f57d5547-1738-4591-b5a0-6fc44a924fba
  PROJECT_NAME: rio-terrain
  GITHUB_REPO_NAME: mrahnis/rio-terrain

  matrix:
    - PYTHON_VERSION: 3.6
      PYTHON_ARCH: 64
      MINICONDA: C:\Miniconda36-x64

init:
  - ps: Write-Host $Env:PYTHON_VERSION
  - ps: Write-Host $Env:MINICONDA
  - ps: Write-Host $Env:GITHUB_REPO_NAME
  - ps: Write-Host $Env:PLATFORM
  - ps: Write-Host $Env:APPVEYOR_REPO_TAG
  - ps: Write-Host $Env:APPVEYOR_REPO_TAG_NAME
  - ps: Write-Host $Env:APPVEYOR_REPO_NAME

install:
  - '"%MINICONDA%\Scripts\activate.bat"'
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda install conda-build conda-verify anaconda-client pytest
  - conda config --add channels conda-forge
  - conda info -a

build: false

test_script:
  - conda build .
  - conda install %PROJECT_NAME% --use-local
  - pytest

after_test:
  - ps: Copy-Item $Env:MINICONDA\conda-bld -Destination . -Recurse

artifacts:
  - path: 'conda-bld\noarch\*.tar.bz2'

on_success:
  - ps: ci\appveyor\deploy_to_anaconda.ps1
