[project]
name = "rio-terrain"
version = "0.1.0"
description = "Add a short description here"
authors = ["mrahnis <mrahnis@users.noreply.github.com>"]
channels = ["conda-forge"]
platforms = ["win-64"]

[tasks]

[dependencies]
crick = ">=0.0.3,<0.1"
matplotlib = ">=3.8.2,<3.9"
scipy = ">=1.11.4,<1.12"
click = ">=8.1.7,<8.2"
numpy = ">=1.26.3,<1.27"
shapely = ">=2.0.2,<2.1"
fiona = ">=1.9.5,<1.10"
rasterio = ">=1.3.9,<1.4"
pip = ">=23.3.2,<23.4"
setuptools = ">=69.0.3,<69.1"
